### ISSUE TITLE
Implicit feedback

### ISSUE THREAD

**Issue by tms1337** [NVIDIA/DeepRecommender#28]
How would I go about applying this model to the implicit feedback, meaning just visiting/non-visiting for example, so not numerical rating?

**Comment by okuchaiev** [comment]
This model is designed for an "explicit" feedback.
However, you could try converting your implicit feedback into numerical scores, e.g. normalized frequency of visits, etc.

**Comment by tms1337** [comment]
@okuchaiev  Do you happen to know some dataset for testing this out, I think it would be beneficial if we confirm this model could be used for implicit feedback also

**Comment by phuctth0512** [comment]
Can I use for implicit feedback like number of clicks on item?
