### ISSUE TITLE
Question about dense re-feeding.

### ISSUE THREAD

**Issue by sainimohit23** [NVIDIA/DeepRecommender#29]
In dense re-feeding what do we show as output to model. For example let's say B is our training batch. For model input `X` and label `y` both will be equal to `B`. Let's say model gives `y_hat` as output for our batch `B`. Now, in dense re-feeding we give this `y_hat` as input to model. Now my question is what will be the labels in dense re-feeding? Will it be `y_hat` or is it `B`?

**Comment by okuchaiev** [comment]
"For model input X and label y both will be equal to B"
-- to be more precise, B=[X,y]
"Let's say model gives y_hat as output for our batch B"
-- the model (f) consumes only X from B, so y_hat=f(x) and we compute loss between y_hat and y
"Now my question is what will be the labels in dense re-feeding? Will it be y_hat or is it B?"
-- In dense re-feeding we feed y_hat again and get y_hat2=f(y_hat), the labels remain the same - y and we compute loss between y_hat2 and y.

**Comment by sainimohit23** [comment]
Thanks @okuchaiev

**Comment by PurushothamanSrikanth** [comment]
@okuchaiev Why do we do Iterative Dense refeeding?
