### ISSUE TITLE
key error when loading the validation dataset

### ISSUE THREAD

**Issue by miguelgfierro** [NVIDIA/DeepRecommender#7]
I'm trying to compute movielens, after downloading movielens 20M, computing the data transformation, when I run the recommender:
`python run.py --gpu_ids 0 --path_to_train_data movielens/train --path_to_eval_data movielens/val --hidden_layers 512,512,1024 --non_linearity_type selu --batch_size 128 --logdir model_movielens --drop_prob 0.8 --optimizer momentum --lr 0.005 --weight_decay 0 --aug_step 1 --noise_prob 0 --num_epochs 1 --summary_frequency 1000`
I get an error:
```bash
Loading training data
Data loaded
Total items found: 138493
Vector dim: 20668
Loading eval data
Traceback (most recent call last):
  File "run.py", line 236, in <module>
    main()
  File "run.py", line 116, in main
    item_id_map=data_layer.itemIdMap)
  File "/home/hoaphumanoid/notebooks/repos/DeepRecommender/reco_encoder/data/input_layer.py", line 48, in __init__
    value = minor_map[int(parts[self._minor_ind])]
KeyError: 18223
```
  It looks that it is trying to find a key in the evaluation dataset that is not in the training dataset?

**Comment by paulhendricks** [comment]
I believe that's exactly what happens...

My understanding is that you have to remove Users and Items from that validation dataset that aren't observed in the training dataset. The Netflix dataset does that here:

https://github.com/NVIDIA/DeepRecommender/blob/master/data_utils/netflix_data_convert.py#L68

Unsure if the MovieLens dataset does this.

**Comment by okuchaiev** [comment]
Yes, this is the case: you need to make sure that all items and users in evaluation are seen at least once in the training set.
